# Importing libraries

In [1]:
import numpy as np
import pandas as pd
import matplotlib.pyplot as plt

import os
from skimage.io import imread
from skimage.transform import resize
from sklearn.model_selection import train_test_split

# Showing image

In [ ]:
plt.figure(figsize=(10,5))
img1 = r"D:\Internship\Prodigy Info Tech\Task-03 Dataset\svm\cats\cat.78.jpg"
plt.imshow(imread(img1))

# Converting image to Matrix/Vector

In [3]:
img_path = r"D:\Internship\Prodigy Info Tech\Task-03 Dataset\svm\cats\cat.78.jpg"
img = imread(img_path)
img

array([[[164, 128, 112],
        [163, 127, 111],
        [163, 127, 111],
        ...,
        [133,  98,  78],
        [133,  98,  78],
        [133,  98,  78]],

       [[162, 126, 110],
        [162, 126, 110],
        [162, 126, 110],
        ...,
        [131,  99,  78],
        [131,  99,  78],
        [131,  99,  78]],

       [[160, 124, 108],
        [160, 124, 108],
        [161, 125, 109],
        ...,
        [131,  99,  76],
        [131,  99,  76],
        [131,  99,  76]],

       ...,

       [[148,  27,  58],
        [150,  29,  60],
        [142,  21,  52],
        ...,
        [156,  31,  63],
        [156,  31,  63],
        [156,  31,  63]],

       [[151,  30,  61],
        [153,  32,  63],
        [143,  22,  53],
        ...,
        [156,  31,  63],
        [156,  31,  63],
        [156,  31,  63]],

       [[153,  32,  63],
        [154,  33,  64],
        [144,  23,  54],
        ...,
        [155,  30,  62],
        [155,  30,  62],
        [155,  30,  62]]

In [4]:
img.shape

(499, 499, 3)

# Resizing the Matrix

In [5]:
img_resize = resize(img, (15, 15))
img_resize.shape

(15, 15, 3)

In [6]:
img_resize

array([[[0.63552634, 0.50096774, 0.43092317],
        [0.64004555, 0.51072077, 0.44057545],
        [0.60233615, 0.48950861, 0.44084657],
        [0.62899958, 0.51845533, 0.48445812],
        [0.61444715, 0.51287531, 0.49604664],
        [0.59735185, 0.49711004, 0.47943283],
        [0.62837062, 0.51792903, 0.49619426],
        [0.63655072, 0.51162727, 0.47065668],
        [0.64052554, 0.50770003, 0.46244281],
        [0.62698549, 0.49473356, 0.44916166],
        [0.61008938, 0.48342112, 0.44115791],
        [0.58881511, 0.46650939, 0.42587228],
        [0.55517477, 0.43273175, 0.37263142],
        [0.5047328 , 0.38779302, 0.30359559],
        [0.49333876, 0.3792029 , 0.29107234]],

       [[0.63104177, 0.50530973, 0.44608144],
        [0.63049812, 0.51164944, 0.45595879],
        [0.49358021, 0.39988367, 0.36405397],
        [0.42990135, 0.34314002, 0.30541649],
        [0.43415809, 0.35216373, 0.32780178],
        [0.449158  , 0.35241563, 0.33831424],
        [0.58391076, 0.47750919,

# Flattening the Matrix/Vector

In [7]:
flatten_img = img_resize.flatten()
flatten_img

array([0.63552634, 0.50096774, 0.43092317, 0.64004555, 0.51072077,
       0.44057545, 0.60233615, 0.48950861, 0.44084657, 0.62899958,
       0.51845533, 0.48445812, 0.61444715, 0.51287531, 0.49604664,
       0.59735185, 0.49711004, 0.47943283, 0.62837062, 0.51792903,
       0.49619426, 0.63655072, 0.51162727, 0.47065668, 0.64052554,
       0.50770003, 0.46244281, 0.62698549, 0.49473356, 0.44916166,
       0.61008938, 0.48342112, 0.44115791, 0.58881511, 0.46650939,
       0.42587228, 0.55517477, 0.43273175, 0.37263142, 0.5047328 ,
       0.38779302, 0.30359559, 0.49333876, 0.3792029 , 0.29107234,
       0.63104177, 0.50530973, 0.44608144, 0.63049812, 0.51164944,
       0.45595879, 0.49358021, 0.39988367, 0.36405397, 0.42990135,
       0.34314002, 0.30541649, 0.43415809, 0.35216373, 0.32780178,
       0.449158  , 0.35241563, 0.33831424, 0.58391076, 0.47750919,
       0.45153912, 0.61225087, 0.4891862 , 0.4457413 , 0.616404  ,
       0.4891188 , 0.44730268, 0.60773888, 0.50582577, 0.48495

In [8]:
flatten_img.shape

(675,)

# Reading the images from image folder and converting them into Matrix. Store it into list

In [9]:
input_dir = r"D:\Internship\Prodigy Info Tech\Task-03 Dataset\svm"
categories = ['cats','dogs']
data = []
labels = []

for category_idx, category in enumerate(categories):
    for file in os.listdir(os.path.join(input_dir, category)):
        img_path = os.path.join(input_dir, category, file)
        print(img_path)
        img = imread(img_path)
        img = resize(img, (15,15))
        data.append(img.flatten())
        labels.append(category_idx)

D:\Internship\Prodigy Info Tech\Task-03 Dataset\svm\cats\cat.10.jpg
D:\Internship\Prodigy Info Tech\Task-03 Dataset\svm\cats\cat.10000.jpg
D:\Internship\Prodigy Info Tech\Task-03 Dataset\svm\cats\cat.10001.jpg
D:\Internship\Prodigy Info Tech\Task-03 Dataset\svm\cats\cat.10007.jpg
D:\Internship\Prodigy Info Tech\Task-03 Dataset\svm\cats\cat.10017.jpg
D:\Internship\Prodigy Info Tech\Task-03 Dataset\svm\cats\cat.10021.jpg
D:\Internship\Prodigy Info Tech\Task-03 Dataset\svm\cats\cat.10026.jpg
D:\Internship\Prodigy Info Tech\Task-03 Dataset\svm\cats\cat.10030.jpg
D:\Internship\Prodigy Info Tech\Task-03 Dataset\svm\cats\cat.10033.jpg
D:\Internship\Prodigy Info Tech\Task-03 Dataset\svm\cats\cat.10035.jpg
D:\Internship\Prodigy Info Tech\Task-03 Dataset\svm\cats\cat.10036.jpg
D:\Internship\Prodigy Info Tech\Task-03 Dataset\svm\cats\cat.10046.jpg
D:\Internship\Prodigy Info Tech\Task-03 Dataset\svm\cats\cat.10048.jpg
D:\Internship\Prodigy Info Tech\Task-03 Dataset\svm\cats\cat.10052.jpg
D:\Intern

In [10]:
data[1]

array([0.03137255, 0.03137255, 0.03137255, 0.03322769, 0.03305075,
       0.0330438 , 0.19158696, 0.1765325 , 0.17613298, 0.44646261,
       0.41192018, 0.40673064, 0.12988979, 0.11959058, 0.10845917,
       0.20538227, 0.18108958, 0.15887506, 0.40104016, 0.36361413,
       0.34559977, 0.08961978, 0.07860259, 0.07412011, 0.05507433,
       0.03864397, 0.03671243, 0.08324351, 0.06229548, 0.03615824,
       0.16682203, 0.13348027, 0.05594513, 0.27475662, 0.22545001,
       0.12389075, 0.3156703 , 0.26257619, 0.16306607, 0.17640112,
       0.14815211, 0.09544955, 0.04273187, 0.04050864, 0.03667778,
       0.03137255, 0.03137255, 0.03137255, 0.03281661, 0.03261613,
       0.03260645, 0.18450694, 0.16376994, 0.16348066, 0.63338051,
       0.57232398, 0.56425019, 0.45008156, 0.41598811, 0.38239841,
       0.46946133, 0.4282015 , 0.38950155, 0.42258561, 0.37920109,
       0.3643736 , 0.07228564, 0.06352144, 0.06214289, 0.0509204 ,
       0.03882308, 0.03537423, 0.0885597 , 0.06336777, 0.03755

In [11]:
labels[1]

0

# List of Matrix converted into Numpy Array

In [12]:
data = np.asarray(data)
labels = np.asarray(labels)

In [13]:
data.shape

(5000, 675)

In [14]:
labels

array([0, 0, 0, ..., 1, 1, 1])

# Splitting the data into training and testing 

In [15]:
x_train, x_test, y_train, y_test = train_test_split(data, labels, test_size=0.2, shuffle=True, stratify=labels)

# Building SVM model for classification

In [16]:
from sklearn.svm import SVC
svm_model = SVC()

# Training the model

In [17]:
svm_model.fit(x_train, y_train)

SVC()

## Prediction of the model

In [18]:
y_pred = svm_model.predict(x_test)
y_pred

array([1, 0, 1, 1, 1, 0, 1, 0, 1, 0, 1, 0, 0, 1, 1, 1, 1, 0, 1, 0, 1, 0,
       0, 1, 0, 0, 0, 1, 0, 1, 1, 1, 1, 0, 0, 1, 0, 1, 1, 0, 0, 0, 1, 0,
       0, 1, 0, 1, 1, 0, 0, 0, 0, 0, 0, 1, 0, 0, 1, 0, 1, 0, 1, 0, 0, 1,
       1, 1, 1, 0, 0, 0, 0, 0, 0, 0, 0, 1, 1, 1, 0, 1, 0, 0, 0, 0, 0, 0,
       1, 1, 1, 1, 1, 1, 0, 1, 0, 1, 0, 0, 0, 1, 1, 1, 1, 1, 1, 0, 0, 0,
       1, 1, 1, 1, 1, 0, 0, 0, 1, 1, 1, 1, 0, 0, 0, 1, 1, 1, 0, 1, 1, 1,
       1, 1, 1, 1, 1, 0, 1, 0, 0, 1, 1, 0, 0, 1, 1, 1, 1, 1, 1, 0, 0, 0,
       1, 0, 1, 0, 0, 0, 1, 1, 1, 0, 1, 0, 1, 0, 1, 1, 1, 0, 0, 1, 1, 0,
       1, 0, 1, 0, 1, 0, 1, 0, 0, 1, 1, 1, 1, 1, 1, 1, 1, 0, 0, 0, 0, 0,
       0, 1, 1, 0, 0, 0, 1, 0, 1, 0, 1, 0, 0, 1, 0, 0, 1, 0, 1, 0, 0, 0,
       0, 1, 1, 0, 1, 1, 1, 1, 1, 1, 1, 0, 0, 0, 0, 1, 1, 0, 0, 1, 0, 0,
       0, 1, 1, 1, 0, 0, 1, 1, 1, 1, 0, 0, 1, 1, 0, 1, 0, 0, 0, 1, 0, 1,
       0, 1, 1, 0, 0, 1, 0, 1, 0, 1, 1, 0, 0, 0, 0, 0, 0, 0, 0, 0, 1, 1,
       1, 0, 1, 1, 0, 0, 0, 1, 0, 1, 0, 0, 1, 1, 1,

# Evaluation of the model

In [19]:
from sklearn.metrics import accuracy_score
score = accuracy_score(y_test, y_pred)
score

0.64

# Cross Validation

In [20]:
from sklearn.model_selection import cross_val_score
cross_val_score = cross_val_score(svm_model, data, labels, cv=5)
cross_val_score

array([0.621, 0.641, 0.65 , 0.654, 0.678])

In [21]:
Mean_Accuracy = cross_val_score.mean()
Mean_Accuracy

0.6487999999999999

In [22]:
from sklearn.metrics import classification_report
print(classification_report(y_test, y_pred))

              precision    recall  f1-score   support

           0       0.64      0.64      0.64       500
           1       0.64      0.64      0.64       500

    accuracy                           0.64      1000
   macro avg       0.64      0.64      0.64      1000
weighted avg       0.64      0.64      0.64      1000

